apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    url: postgres:5432
    database: bus_analytics
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: true
